fixtures:
  repositories:
    yumrepo_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-yumrepo_core'
      puppet_version: '>= 6.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib'
